[Docs-1290]  Document old public api as deprecated
dominodatalab/api-docs pull request #48
Opened 2022-06-30 18:51 UTC by Russ-Urquhart-ddl

Jira:
https://dominodatalab.atlassian.net/browse/DOCS-1290

Deprecated the old endpoints and provided links to new public endpoints.

2022-06-30 19:56 UTC, noahjax commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_project_by_id).**
This should be the endpoint for retrieving a list of projects, not getting a single project.

2022-07-01 01:13 UTC, ddl-lgaddie requested changes

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_environments_visible_to_a
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_environments_visible_to_a_user).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_all_users_visible_to_the_
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_all_users_visible_to_the_current_user).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_the_current_user).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_the_current_user).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_all_organizations_only_ac
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_all_organizations_only_accessible_to_admin_users).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_create_an_organization).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_create_an_organization).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_the_organizations_for_a_u
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_the_organizations_for_a_user).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_an_organization_by_id.)**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_an_organization_by_id.)**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [ADD endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_add_a_user_to_an_org) and the [DE
```suggestion
**This endpoint is deprecated. For more information, see the [ADD endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_add_a_user_to_an_org) and the [DELETE endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_remove_a_user_from_an_org).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_project_by_id).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_project_by_id).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_create_a_project).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_create_a_project).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_add_a_collaborator_to_this_pr
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_add_a_collaborator_to_this_project).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_remove_a_collaborator_from_pr
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_remove_a_collaborator_from_project).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_all_imported_git_reposito
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_all_imported_git_repositories_in_this_project).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_add_an_imported_git_repositor
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_add_an_imported_git_repository_to_this_project).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_remove_an_imported_repository
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_remove_an_imported_repository_from_project).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_datasets_visible_to_user)
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_datasets_visible_to_user).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_dataset_by_id).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_dataset_by_id).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_update_dataset_metadata).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_update_dataset_metadata).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_delete_dataset).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_delete_dataset).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_snapshot).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_snapshot).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_create_a_snapshot).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_create_a_snapshot).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_create_a_dataset).**
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_create_a_dataset).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_tag_a_snapshot_in_this_datase
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_tag_a_snapshot_in_this_dataset).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_remove_a_tag_from_a_dataset).
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_remove_a_tag_from_a_dataset).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_projects_visible_to_user)
```suggestion
**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/latest/api_guide/8c929e/domino-public-apis/#_get_projects_visible_to_user).**
```

2022-07-01 01:13 UTC, ddl-lgaddie commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_environments_visible_to_a
@Russ-Urquhart-ddl Let's do it this way unless we have reason to believe that the new endpoints won't be in 5.3 and up.

2022-07-04 15:15 UTC, Russ-Urquhart-ddl commented on apiary.apib
> +**This endpoint is deprecated. For more information, see the [current endpoint documentation](https://docs.dominodatalab.com/en/5.2/api_guide/8c929e/domino-public-apis/#_get_environments_visible_to_a
Ok, I originally had it as latest, but changed it to 5.2 as per the Readme. I can change back.

2022-07-05 18:39 UTC, ddl-lgaddie approved these changes

2022-07-06 15:51 UTC, merged